Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2021-09, with the labels that each got.

#210 Kube burner workloads
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/env.sh
  workloads/kube-burner/kube-burner-crd.yaml
  workloads/kube-burner/metrics-profiles/metrics-aggregated.yml
  workloads/kube-burner/metrics-profiles/metrics.yml
  workloads/kube-burner/run_clusterdensity_test_fromgit.sh
  workloads/kube-burner/run_custom_workload_fromgit.sh
  workloads/kube-burner/run_maxnamespaces_test_fromgit.sh
  workloads/kube-burner/run_maxservices_test_fromgit.sh
  workloads/kube-burner/run_nodedensity-heavy_test_fromgit.sh
  workloads/kube-burner/run_nodedensity_test_fromgit.sh
  workloads/kube-burner/run_poddensity_test_fromgit.sh
  workloads/kube-burner/workloads/cluster-density/cluster-density.yml
  workloads/kube-burner/workloads/cluster-density/templates/build.yml
  workloads/kube-burner/workloads/cluster-density/templates/buildconfig.yml
  workloads/kube-burner/workloads/cluster-density/templates/configmap.yml
  workloads/kube-burner/workloads/cluster-density/templates/deployment.yml
  workloads/kube-burner/workloads/cluster-density/templates/imagestream.yml
  workloads/kube-burner/workloads/cluster-density/templates/route.yml
  workloads/kube-burner/workloads/cluster-density/templates/secret.yml
  workloads/kube-burner/workloads/cluster-density/templates/service.yml
  workloads/kube-burner/workloads/max-namespaces/max-namespaces.yml
  workloads/kube-burner/workloads/max-namespaces/templates/app-deployment.yml
  workloads/kube-burner/workloads/max-namespaces/templates/postgres-deployment.yml
  workloads/kube-burner/workloads/max-namespaces/templates/postgres-service.yml
  workloads/kube-burner/workloads/max-namespaces/templates/secret.yml
  workloads/kube-burner/workloads/max-services/max-services.yml
  workloads/kube-burner/workloads/max-services/templates/deployment.yml
  workloads/kube-burner/workloads/max-services/templates/service.yml
  workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml
  workloads/kube-burner/workloads/node-density-heavy/templates/app-deployment.yml
  workloads/kube-burner/workloads/node-density-heavy/templates/postgres-deployment.yml
  workloads/kube-burner/workloads/node-density-heavy/templates/postgres-service.yml
  workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
  workloads/kube-burner/workloads/node-pod-density/templates/pod.yml
Labels: enhancement, ok to test

#229 Rename VERSION parameter to prevent conflict with benchmark-operator…
  ci/env.sh
  workloads/scale-perf/common.sh
  workloads/upgrade-perf/README.md
  workloads/upgrade-perf/common.sh
  workloads/upgrade-perf/run_upgrade_fromgit.sh
Labels: bug, ok to test

#233 Fix cluster-density variables
  workloads/kube-burner/env.sh
  workloads/kube-burner/workloads/cluster-density/cluster-density.yml
  workloads/kube-burner/workloads/cluster-density/templates/configmap.yml
  workloads/kube-burner/workloads/cluster-density/templates/deployment.yml
  workloads/kube-burner/workloads/cluster-density/templates/secret.yml
Labels: bug, ok to test

#222 Scale ingress controller down to 0 before setting liveness probe
  workloads/router-perf-v2/common.sh
Labels: bug, ok to test

#236 Fix in maxnamespaces and maxservices kube-burner workloads
  workloads/kube-burner/run_maxnamespaces_test_fromgit.sh
  workloads/kube-burner/run_maxservices_test_fromgit.sh
Labels: bug

#242 Adding missing env variable to env.sh and README
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/env.sh
Labels: ok to test

#245 add export to gsheet and email variables in env file
  workloads/router-perf-v2/env.sh
Labels: ok to test

#251 Sleep 10s before next run
  workloads/scale-perf/README.md
  workloads/scale-perf/run_scale_fromgit.sh
Labels: ok to test

#243 add ROSA variables to scale script
  workloads/scale-perf/README.md
  workloads/scale-perf/common.sh
  workloads/scale-perf/default_scale.yaml
  workloads/scale-perf/rosa_scale.yaml
  workloads/scale-perf/run_scale_fromgit.sh
Labels: enhancement, ok to test

#253 CPU and memory by node role plus failed pods breakdown
  workloads/kube-burner/metrics-profiles/metrics-aggregated.yml
  workloads/kube-burner/metrics-profiles/metrics.yml
Labels: enhancement
