Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2021-03, with the labels that each got.

#97 Add scripts to index jenkins job status
  indexing/README.md
  indexing/jenkins/README.md
  indexing/jenkins/index.sh
Labels: needs testing

#135 added a node to scale option , default worker
  workloads/scale-perf/README.md
  workloads/scale-perf/common.sh
  workloads/scale-perf/run_scale_fromgit.sh
Labels: ok to test

#124 Router perf v2
  ci/CI_test_list.yml
  ci/README.md
  ci/env.sh
  utils/touchstone-compare/run_compare.sh
  workloads/kube-burner/README.md
  workloads/network-perf/common.sh
  workloads/network-perf/run_multus_network_tests_fromgit.sh
  workloads/router-perf-v2/Containerfile
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/common.sh
  workloads/router-perf-v2/csv_gen.py
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/http-perf.yml.tmpl
  workloads/router-perf-v2/ingress-performance.sh
  workloads/router-perf-v2/templates/edge-route.yml
  workloads/router-perf-v2/templates/http-client-rolebinding.yml
  workloads/router-perf-v2/templates/http-client-sa.yml
  workloads/router-perf-v2/templates/http-route.yml
  workloads/router-perf-v2/templates/http-scale-client.yml
  workloads/router-perf-v2/templates/http-service.yml
  workloads/router-perf-v2/templates/nginx-pod.yml
  workloads/router-perf-v2/templates/passthrough-route.yml
  workloads/router-perf-v2/templates/reencrypt-route.yml
  workloads/router-perf-v2/workload.py
  workloads/router-perf/run_router_test.sh
Labels: enhancement, ok to test

#130 Enable targeted log forwarding
  workloads/logging/README.md
  workloads/logging/deploy_logging_stack.sh
  workloads/logging/env.sh
  workloads/logging/files/elasticsearch-route.yml
  workloads/logging/files/logging-stack.yml
Labels: P2

#137 Tune workload node
  workloads/router-perf-v2/common.sh
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/ingress-performance.sh
  workloads/router-perf-v2/tuned-profile.yml
Labels: ok to test

#148 Deprecate router-perf in favor of router-perf-v2
  ci/CI_test_list.yml
  ci/env.sh
  workloads/router-perf/README.md
  workloads/router-perf/csv_gen.py
  workloads/router-perf/env.sh
  workloads/router-perf/requirements.txt
  workloads/router-perf/run_router_test.sh
Labels: ok to test

#150 Renaming variables in the spirit of consistency
  workloads/kube-burner/README.md
  workloads/kube-burner/run_maxnamespaces_test_fromgit.sh
  workloads/kube-burner/run_maxservices_test_fromgit.sh
Labels: enhancement, ok to test

#158 Update CI vars to match new naming
  ci/env.sh
  workloads/network-perf/common.sh
Labels: ok to test
