Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2022-02, with the labels that each got.

#308 clear temp/ripsaw directory before running ci tests
  ci/run_ci.sh
Labels: ok to test

#300 Adding python3 specific version to touchstone installation
  utils/compare.sh
Labels: bug

#310 fix kube-burner cleanup function
  workloads/kube-burner/common.sh
Labels: ok to test

#314 Bump kube-burner to v0.15.1 and preload kube-burner images
  workloads/kube-burner/README.md
  workloads/kube-burner/env.sh
  workloads/kube-burner/workloads/cluster-density/cluster-density.yml
  workloads/kube-burner/workloads/max-namespaces/max-namespaces.yml
  workloads/kube-burner/workloads/max-services/max-services.yml
  workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml
  workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
  workloads/kube-burner/workloads/pod-density-heavy/pod-density-heavy.yml
Labels: enhancement, ok to test

#323 Bump kube-burner v0.15.2
  workloads/kube-burner/env.sh
Labels: bug, ok to test
