Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2022-03, with the labels that each got.

#318 Kube burner metrics refactor
  workloads/kube-burner/metrics-profiles/metrics-aggregated.yaml
  workloads/kube-burner/metrics-profiles/metrics.yaml
Labels: ok to test

#324 Unify networking benchmarks
  ci/CI_test_list.yml
  utils/benchmark-operator.sh
  utils/compare.sh
  workloads/kube-burner/README.md
  workloads/network-perf/README.md
  workloads/network-perf/common.sh
  workloads/network-perf/env.sh
  workloads/network-perf/ripsaw-uperf-crd.yaml
  workloads/network-perf/run.sh
  workloads/network-perf/run_hostnetwork_network_test_fromgit.sh
  workloads/network-perf/run_multus_network_tests_fromgit.sh
  workloads/network-perf/run_pod_network_policy_test_fromgit.sh
  workloads/network-perf/run_pod_network_test_fromgit.sh
  workloads/network-perf/run_serviceip_metallb_network_test_fromgit.sh
  workloads/network-perf/run_serviceip_network_policy_test_fromgit.sh
  workloads/network-perf/run_serviceip_network_test_fromgit.sh
  workloads/network-perf/run_serviceip_nodeport_network_test_fromgit.sh
  workloads/network-perf/smoke-crd.yaml
  workloads/network-perf/smoke_test.sh
  workloads/network-perf/uperf-touchstone-smoke.json
Labels: ok to test

#329 Run hostNetwork with only 1 pair
  workloads/network-perf/README.md
  workloads/network-perf/run.sh
Labels: bug

#327 Print pod info on error
  utils/benchmark-operator.sh
Labels: enhancement, ok to test

#338 Unify kube burner
  .gitignore
  ci/CI_test_list.yml
  ci/run_ci.sh
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/run.sh
  workloads/kube-burner/run_clusterdensity_test_fromgit.sh
  workloads/kube-burner/run_custom_workload_fromgit.sh
  workloads/kube-burner/run_maxnamespaces_test_fromgit.sh
  workloads/kube-burner/run_maxservices_test_fromgit.sh
  workloads/kube-burner/run_nodedensity-heavy_test_fromgit.sh
  workloads/kube-burner/run_nodedensity_test_fromgit.sh
  workloads/kube-burner/run_poddensity-heavy_test_fromgit.sh
  workloads/kube-burner/run_poddensity_test_fromgit.sh
Labels: enhancement, ok to test

#343 Align default pods per node to new standard of 245
  workloads/kube-burner/README.md
  workloads/kube-burner/run.sh
Labels: ok to test

#342 Set pod resources in node-density workloads
  workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml
  workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
  workloads/kube-burner/workloads/node-pod-density/pod.yml
Labels: enhancement, ok to test

#339 Fix cluster type detection being too specific
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/http-perf.yml.tmpl
  workloads/router-perf-v2/templates/http-scale-client.yml
  workloads/router-perf-v2/workload.py
Labels: ok to test

#345 Don't exit 1 on benchmark error
  utils/benchmark-operator.sh
Labels: enhancement, ok to test

#313 Add CNI focussed node-density workloads
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/run.sh
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/allow-http.yml
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/curl-deployment.yml
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/deny-all.yml
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/webserver-deployment.yml
  workloads/kube-burner/workloads/node-density-cni-networkpolicy/webserver-service.yml
  workloads/kube-burner/workloads/node-density-cni/curl-deployment.yml
  workloads/kube-burner/workloads/node-density-cni/node-density-cni.yml
  workloads/kube-burner/workloads/node-density-cni/webserver-deployment.yml
  workloads/kube-burner/workloads/node-density-cni/webserver-service.yml
Labels: ok to test

#347 Add metric for pod distribution by node
  workloads/kube-burner/metrics-profiles/metrics.yaml
Labels: ok to test

#346 Index benchmark metadata
  utils/benchmark-operator.sh
  utils/common.sh
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/run.sh
  workloads/network-perf/env.sh
  workloads/scale-perf/env.sh
Labels: ok to test

#354 Add ovnkube_master_sync_service_latency_seconds_bucket metric
  workloads/kube-burner/metrics-profiles/metrics-aggregated.yaml
  workloads/kube-burner/metrics-profiles/metrics.yaml
Labels: enhancement, ok to test

#357 Include workload field as metadata
  utils/common.sh
Labels: enhancement, ok to test
