Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2022-04, with the labels that each got.

#351 Cluster-density refactor
  workloads/kube-burner/README.md
  workloads/kube-burner/env.sh
  workloads/kube-burner/workloads/cluster-density/buildconfig.yml
  workloads/kube-burner/workloads/cluster-density/cluster-density.yml
  workloads/kube-burner/workloads/cluster-density/configmap.yml
  workloads/kube-burner/workloads/cluster-density/deployment.yml
  workloads/kube-burner/workloads/cluster-density/imagestream.yml
  workloads/kube-burner/workloads/cluster-density/service.yml
Labels: enhancement

#168 Adding concurrent builds test for benchmark operator
  workloads/kube-burner/README.md
  workloads/kube-burner/build_helper.sh
  workloads/kube-burner/builds/cakephp.sh
  workloads/kube-burner/builds/django.sh
  workloads/kube-burner/builds/eap.sh
  workloads/kube-burner/builds/nodejs.sh
  workloads/kube-burner/builds/rails.sh
  workloads/kube-burner/common.sh
  workloads/kube-burner/env.sh
  workloads/kube-burner/run.sh
  workloads/kube-burner/workloads/concurrent-builds/buildconfig_trigger.yml
  workloads/kube-burner/workloads/concurrent-builds/concurrent-builds.yml
  workloads/kube-burner/workloads/concurrent-builds/configmap.yml
  workloads/kube-burner/workloads/concurrent-builds/imagestream.yml
Labels: ok to test

#374 Set targeted to false for metadata collection by default
  workloads/network-perf/README.md
  workloads/network-perf/env.sh
Labels: ok to test

#365 Modify how ROSA is detected as platform and move from cloud_type to platform
  utils/common.sh
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/http-perf.yml.tmpl
  workloads/router-perf-v2/templates/http-scale-client.yml
  workloads/router-perf-v2/workload.py
Labels: ok to test

#376 Skip certificate validation
  utils/common.sh
  workloads/etcd-perf/run_etcd_tests_fromgit.sh
  workloads/router-perf-v2/workload.py
Labels: ok to test

#372 Moving remove cli till after gen metadata and only if failure
  utils/benchmark-operator.sh
  workloads/kube-burner/build_helper.sh
  workloads/kube-burner/run.sh
  workloads/logging/run_logging_test.sh
  workloads/network-perf/run.sh
  workloads/scale-perf/run_scale_fromgit.sh
Labels: ok to test

#380 Use unauthenticated repository for postgres image
  workloads/kube-burner/workloads/max-namespaces/postgres-deployment.yml
  workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
Labels: ok to test

#363 Template out infrastructure to match with TERMINATIONS
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/http-perf.yml.tmpl
Labels: enhancement, ok to test

#390 Template out infrastructure to match with TERMINATIONS
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/env.sh
  workloads/router-perf-v2/http-perf.yml.tmpl
Labels: ok to test
