Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2022-06, with the labels that each got.

#415 Bump kube-burner version
  workloads/kube-burner/README.md
  workloads/kube-burner/env.sh
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/env.sh
Labels: ok to test

#420 Fix prometheus token expression for k8s 1.24
  workloads/kube-burner/common.sh
Labels: bug

#418 Remove export NODE_SELECTOR
  workloads/kube-burner/common.sh
Labels: ok to test

#413 Remove benchmark-operator's role dependencies
  utils/benchmark-operator.sh
  workloads/cyclictest/common.sh
  workloads/etcd-perf/run_etcd_tests_fromgit.sh
  workloads/kube-burner/common.sh
  workloads/logging/common.sh
  workloads/network-perf/common.sh
  workloads/network-perf/ripsaw-uperf-crd.yaml
  workloads/network-perf/smoke-crd.yaml
  workloads/oslat/common.sh
  workloads/scale-perf/common.sh
  workloads/testpmd/common.sh
Labels: ok to test

#424 Bump kube-burner version to v0.16
  workloads/kube-burner/README.md
  workloads/kube-burner/env.sh
  workloads/router-perf-v2/README.md
  workloads/router-perf-v2/env.sh
Labels: enhancement, ok to test

#427 Refactored run_workload method duplicated in the workloads
  utils/benchmark-operator.sh
  workloads/api-load/common.sh
  workloads/api-load/run.sh
  workloads/cyclictest/common.sh
  workloads/network-perf/common.sh
  workloads/oslat/common.sh
  workloads/scale-perf/common.sh
  workloads/testpmd/common.sh
Labels: ok to test

#429 Update workloads with multiarch images for ARM testing support
  workloads/kube-burner/workloads/max-namespaces/postgres-deployment.yml
  workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
  workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
  workloads/prometheus-sizing/prometheus-sizing-churning.yml
  workloads/prometheus-sizing/prometheus-sizing-static.yml
  workloads/router-perf-v2/templates/nginx-deploy.yml
Labels: ok to test

#425 Decrease verbosity of kube-burner tests
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/env.sh
  workloads/kube-burner/run.sh
Labels: enhancement, ok to test
