Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2024-07, with the labels that each got.

#710 Fix quotes on ARO vars
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#713 Fixing broken oc binary
  prow/Dockerfile
Labels: lgtm, approved

#712 Ingress-perf config for scalelab CPT jobs
  workloads/ingress-perf/config/standard-scalelab.yml
Labels: enhancement, lgtm, approved

#709 [PERFSCALE-1802] Enable HTTP2 for reencrypt/passthrough terminations
  workloads/ingress-perf/config/standard-classic-rosa.yml
  workloads/ingress-perf/config/standard-scalelab.yml
  workloads/ingress-perf/config/standard.yml
  workloads/ingress-perf/run.sh
Labels: approved

#714 Updaing to kube-burner v1.3.0
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#715 Fixing errata in baremetal http2 config
  workloads/ingress-perf/config/standard-scalelab.yml
Labels: approved
