Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2024-06, with the labels that each got.

#700 bumped k8s-v0.1.22
  workloads/network-perf-v2/env.sh
Labels: lgtm, approved, needs-ok-to-test

#701 Discard ITERATIONS when running web-burner
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved, needs-ok-to-test

#699 Support egressip scale testing
  workloads/kube-burner-ocp-wrapper/README.md
  workloads/kube-burner-ocp-wrapper/egressip.sh
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#694 [PERFSCALE-2994]: Updates to SDN-->OVNK Script
  workloads/sdn2ovn/README.md
  workloads/sdn2ovn/run.sh
Labels: lgtm, approved

#702 Sdn ovnk
  workloads/sdn2ovn/run.sh
Labels: lgtm, approved

#704 Updating kube-burner release to latest version
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#698 aro hcp metric profile
  workloads/kube-burner-ocp-wrapper/README.md
  workloads/kube-burner-ocp-wrapper/alerts-profiles/aro/hosted-cluster-alerts.yml
  workloads/kube-burner-ocp-wrapper/alerts-profiles/aro/hosted-cp-alerts.yml
  workloads/kube-burner-ocp-wrapper/alerts-profiles/rosa/hosted-cluster-alerts.yml
  workloads/kube-burner-ocp-wrapper/alerts-profiles/rosa/hosted-cp-alerts.yml
  workloads/kube-burner-ocp-wrapper/metrics-endpoint.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/hosted-cluster-metrics.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/hosted-cp-metrics.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/mc-metrics.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/rosa/hosted-cluster-metrics.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/rosa/hosted-cp-metrics.yml
  workloads/kube-burner-ocp-wrapper/metrics-profiles/rosa/mc-metrics.yml
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: approved

#705 update kb-ocp version to latest
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: approved

#691 Bump the ingress-version to 0.4.2
  workloads/ingress-perf/run.sh
Labels: lgtm, approved

#706 Fixing run.sh
  workloads/network-perf-v2/run.sh
Labels: lgtm, approved

#707 Bumping up k8s-netperf to v0.1.23
  workloads/network-perf-v2/env.sh
Labels: approved

#708 Update hypershift on aks to calculate the token
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved
