Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2025-03, with the labels that each got.

#752 Updaing dockerfile to be inline with openshift CI
  prow/Dockerfile
Labels: lgtm, approved

#754 Make egress-ip CI ready
  workloads/kube-burner-ocp-wrapper/egressip.sh
Labels: lgtm, approved

#755 Remove unnecessary timestamp fields
  utils/index.sh
Labels: lgtm, approved

#759 Adding support for rds-core
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#760 Only rds-core workload supports the perf-profile flag
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: ok to test, lgtm, approved

#742 Use k8s-netperf's serverIP flag
  workloads/network-perf-v2/README.md
  workloads/network-perf-v2/env.sh
  workloads/network-perf-v2/run.sh
Labels: ok to test, lgtm, approved

#753 deprecate network-policy-v1 test cases
  workloads/kube-burner-ocp-wrapper/run.sh
  workloads/kube-burner/README.md
  workloads/kube-burner/common.sh
  workloads/kube-burner/run.sh
  workloads/kube-burner/workloads/networkpolicy/README.md
  workloads/kube-burner/workloads/networkpolicy/case1-networkpolicy.yml
  workloads/kube-burner/workloads/networkpolicy/case1.yml
  workloads/kube-burner/workloads/networkpolicy/case2-networkpolicy.yml
  workloads/kube-burner/workloads/networkpolicy/case2.yml
  workloads/kube-burner/workloads/networkpolicy/case3-networkpolicy.yml
  workloads/kube-burner/workloads/networkpolicy/case3.yml
  workloads/kube-burner/workloads/networkpolicy/clusterrole.yml
  workloads/kube-burner/workloads/networkpolicy/clusterrolebinding.yml
  workloads/kube-burner/workloads/networkpolicy/deny-all.yml
  workloads/kube-burner/workloads/networkpolicy/image/Dockerfile
  workloads/kube-burner/workloads/networkpolicy/image/init.sh
  workloads/kube-burner/workloads/networkpolicy/image/pod-scraper.py
  workloads/kube-burner/workloads/networkpolicy/image/requirements.txt
  workloads/kube-burner/workloads/networkpolicy/nginx.yml
  workloads/kube-burner/workloads/networkpolicy/service.yml
Labels: ok to test, lgtm, approved

#758 [ingress-perf] add GATEWAY_API env to enable gateway api
  workloads/ingress-perf/run.sh
Labels: lgtm, approved

#763 Bug fix
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved, ok-to-test

#762 Update owners and bug assignees
  .github/ISSUE_TEMPLATE/bug_report.md
  OWNERS
Labels: lgtm, approved

#761 Make additional Virt metadata capturing optional
  utils/index.sh
Labels: ok to test, lgtm, approved
