Repository cloud-bulldozer/e2e-benchmarking, pull requests merged in 2025-09, with the labels that each got.

#790 Remove PPROF env var
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#794 Update OWNERS
  OWNERS
Labels: lgtm, approved

#789 kube-burner-ocp-wrapper: auto-detect OS and hardware before downloading the binary
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#740 update channels for logging
  workloads/logging/env.sh
  workloads/logging/files/logging-stack.yml
Labels: ok to test, lgtm, needs-ok-to-test

#792 Handle cases when a periodic job is triggered via PR
  utils/index.sh
Labels: bug, lgtm, approved, do-not-merge/hold

#796 bump kube burner-ocp to 1.7.5
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#795 Add udn-bgp workload
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#798 Using analyze option on helper script.
  workloads/kube-burner/build_helper.sh
  workloads/kube-burner/workloads/concurrent-builds/buildconfig_trigger.yml
Labels: lgtm, approved

#804 bump kube-burner-ocp to 1.7.6
  workloads/kube-burner-ocp-wrapper/run.sh
Labels: lgtm, approved

#805 write uuid to a file
  utils/index.sh
Labels: ok to test, lgtm, approved, needs-ok-to-test
